DROP TABLE IF EXISTS MST_USER_TASK_SETTING_SELECT

CREATE TABLE MST_USER_TASK_SETTING_SELECT
(
		USER_NO					CHAR(6)			NOT NULL	PRIMARY KEY
	,	TASK_STATUS_CODE		CHAR(2)			NOT NULL
	,	TASK_KIND_CODE			CHAR(2)			NOT NULL
	,	TASK_GROUP_CODE			CHAR(2)			NOT NULL
)

INSERT INTO MST_USER_TASK_SETTING_SELECT
VALUES
(
		'000000'
	,	'00'
	,	'00'
	,	'00'
)

INSERT INTO MST_USER_TASK_SETTING_SELECT
VALUES
(
		'000001'
	,	'00'
	,	'00'
	,	'00'
)

INSERT INTO MST_USER_TASK_SETTING_SELECT
VALUES
(
		'999999'
	,	'00'
	,	'00'
	,	'00'
)