SELECT * INTO TRN_TASK_LIST_BK_20190415 FROM TRN_TASK_LIST

DROP TABLE IF EXISTS TRN_TASK_LIST

CREATE TABLE TRN_TASK_LIST
(
		TASK_NO					CHAR(7)			NOT NULL
	,	USER_NO					CHAR(6)			NOT NULL
	,	CREATE_YMD				DATE			NOT NULL
	,	UPDATE_YMD				DATE			NULL
	,	TODO_YMD				DATE			NOT NULL
	,	FINISHED_YMD			DATE			NULL
	,	TASK_STATUS_CODE		NCHAR(2)		NOT NULL
	,	TASK_KIND_CODE			NCHAR(2)		NOT NULL
	,	TASK_GROUP_CODE			NCHAR(2)		NOT NULL
	,	TASK_NAME				VARCHAR(100)	NOT NULL
	,	PLAN_TIME				TIME			NOT NULL
	,	RESULT_TIME				TIME			NOT NULL
	,	MEMO					VARCHAR(400)	NULL
	PRIMARY KEY(TASK_NO, USER_NO)
)

INSERT INTO TRN_TASK_LIST
SELECT 
			TASK_NO				
	   	,	USER_NO				
	   	,	CREATE_YMD			
	   	,	UPDATE_YMD			
	   	,	TODO_YMD			
	   	,	CASE WHEN TASK_STATUS_CODE <> '10' --çœÇ≈Ç»Ç¢É^ÉXÉN
				 THEN NULL
				 WHEN UPDATE_YMD IS NOT NULL
				 THEN UPDATE_YMD
				 ELSE TODO_YMD
			END
	   	,	TASK_STATUS_CODE	
	   	,	TASK_KIND_CODE		
	   	,	TASK_GROUP_CODE		
	   	,	TASK_NAME			
	   	,	PLAN_TIME			
	   	,	RESULT_TIME			
	   	,	MEMO				
FROM TRN_TASK_LIST_BK_20190415

SELECT * FROM TRN_TASK_LIST